ImanMohi/RTU-DigitalLibrary

- Python Programs/reversedLinkList.py
- README.md
added reversed link list program in python
and updated README.md
> added reversedlinklist program in python

- C Programs/RevLL.cpp
As per you assigned me i have sent a PR please approve it
> Added Reverselinkedlist program in C

- C Programs/PrimeNum.c
This is the program which finds all the prime numbers in a given range(given by user)
> Prime Numbers 

- C++ Programs/DFS.cpp
- C++ Programs/Pattern_replace.cpp
- C++ Programs/infix_to_postfix.cpp
- C++ Programs/intToStr.cpp
Added 4 new codes.
DFS, Infix to postfix conversion, Convert integer input to string, and Find and replace pattern in given string.
> Added 4 new C++ examples

- Python_Programs/BubbleSort.py
- Python_Programs/MatrixMultiplication.py
> Bubble sort

- Python_Programs/MatrixMultiplication.py
Matrix Multiplication
Issue #2
> add matrix multiplication

- ArmstrongNumber.c
This program is used to check the given number(by user) is Armstrong number or not (using C language).
> Armstrong Number

- C++ Programs/palindrome_number.cpp
A program to Check weather giver no. is palindrome or not
> palindrome_number.cpp

- C Programs/QuickSort.c
I've a made a PR by adding quick sort program in c . Plz review it and merge it. Thanks.
> Added Quick sort

- C Programs/InsertionSort.c
i've made a PR by adding insertion sort program. plz review it an merge it.Thanks.
> Added insertion sort

- C++ Programs/KaratsubaAlgorithm.cpp
- C++ Programs/MultiplicationOfbinary.cpp
Here, the multiplication of binary numbers is performed using Karatsuba Multiplication(Divide and Conquer) in cpp
> Multiplication Of Binary Numbers

- C Programs/area-of-square.c
Just added a c program to find the area of a square.
> c program to find the area of a square

- C Programs/area-of-circle.c
just added a new c program to find the area of circle.
> c program to find the area of circle

- Python_Programs/find_largest_no_iin_array.py
Python Program to find largest element in an array
I was here making pr for hactoberfest !!
> Create  find_largest_no_iin_array.py

- Python Program to Illustrate Different Set Operations
Python Program to Illustrate Different Set Operations
> Create Python Program to Illustrate Different Set Operations

- Python_Programs/Hangman Game
A game for entertainment.I was here.Making a PR for HactoberFest.
> Create Hangman Game

- Python_Programs/Python Program to Convert Decimal to Binary Using Recursion
Python Program to Convert Decimal to Binary Using Recursion
> Create Python Program to Convert Decimal to Binary Using Recursion

- C Programs/BubbleSort.c
> BubbleSort.c

- Python_Programs/Palindrome
Created a python program for palindrome number.
> Created a python program for palindrome number

- Python_Programs/text_encrypt_algo.py
Simple text encrypting algorithm
> Created text_encrypt_algo.py file

- C Programs/calculator in C++
Simple Calculator using switch statement in C++
> calculator in C++

- Python_Programs/adding_watermark_to_PDF.py
It is a easy mini-project for python beginners
> Adding Watermark to PDF

- C++ Programs/segtreeSumRange.cpp
I was here to make a PR for hacktober fest.
> Added the Sum Range Query Solution using Segment Tree in CPP.

- C++ Programs/knapsack.cpp
I was here to make a PR for hacktober fest.
> Added solution for knapsack problem using cpp

- C Programs/ChainMatrixMultiplication
To Find Minimum Multiplication Needed For Matrix Multiplication
> ChainMatrixMultiplication

- C++ Programs/Bubble sort.cpp
Sorting a given array of size n using Bubble sort
> Create Bubble sort.cpp

- Python_Programs/HCF_GCD.py
Here, two integers variables num1 and num2 are taken from the user.
We first determine the smaller of the two numbers since the H.C.F can only be less than or equal to the smallest number. We then use a for loop to go from 1 to that number.
In each iteration, we check if our number perfectly divides both the input numbers. If so, we store the number as H.C.F. At the completion of the loop, we end up with the largest number that perfectly divides both the numbers.
> Greatest Common Factor(GCD) added

- Java Programs/bubble sort in java
hey !! i was there for hacktoberfest
> bubble sort in java

- Java Programs/LinkedQueue.java
> Hacktoberfest pr

- Frequency program
this is use to measure the frequency of a number.
> Frequency Program

- C Programs/Fibonacci.c
Created a code for fibonacci series
> Fibonaaci.c

- Bank account.cpp
I am here to make my PR for Hacktoberfest 2020
> Create Bank account.cpp

- C Programs/Linkedlist.cpp
I'm here to PR for acktoberfest
> Linkedlist

- C++ Programs/BMICalculator.cpp
Added simple C++ app which calculates your BMI
> Add BMICalculator.cpp

- C Programs/calculator in C.c
Calculator for addition, substraction, multiplication, and print N numbers in C language.
> Calculator in C for Addition, Substraction, Multiplication, and Print N numbers.

- C Programs/Line Clipping | (Cohen–Sutherland Algorithm).c
> Create Line Clipping | (Cohen–Sutherland Algorithm).c

- C Programs/Fibonacci Series up to n terms
c program for fibonacci series
> Create Fibonacci Series up to n terms
